version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: icinema_db
      MYSQL_USER: ramesh8850
      MYSQL_PASSWORD: R@mesh8850
    ports:
      - "3307:3306" # Map to 3307 to avoid conflict with local MySQL
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - icinema-net

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - icinema-net

  app:
    build: .
    depends_on:
      - mysqldb
      - redis
    ports:
      - "8080:8080"
    environment:
      # Profile
      SPRING_PROFILES_ACTIVE: prod
      # Database
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Security
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      JWT_SECRET: ${JWT_SECRET}
      # Mail (Testing Gmail)
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      # SPRING_MAIL_HOST: mailhog
      # SPRING_MAIL_PORT: 1025
    networks:
      - icinema-net
    restart: on-failure

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - icinema-net

volumes:
  db_data:


networks:
  icinema-net:
