services:
  - type: web
    name: icinema-backend
    env: docker
    plan: free
    buildCommand: docker build -t icinema-backend .
    startCommand: docker run icinema-backend
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-url.onrender.com
      - key: SPRING_PROFILES_ACTIVE
        value: prod
